dist: trusty
os: linux
language: java
jdk:
  - oraclejdk8

notifications:
  email:
    on_success: change

jobs:
  include:
    - stage: "Run Tests"
      script:
        - jdk_switcher use oraclejdk8
        - mvn clean test
