dist: bionic
os: linux
language: java
jdk:
  - openjdk8
services:
- docker
notifications:
  email:
    on_success: change
before_install:
  - java -version
  - openssl aes-256-cbc -K $encrypted_955c10630a82_key -iv $encrypted_955c10630a82_iv -in .secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - cp settings.xml $HOME/.m2/
  - gpg --batch --import key.gpg
  - export GPG_TTY=$(tty)
jobs:
  include:
  - stage: Run Build
    cache:
      directories:
      - "$HOME/.m2"
    script:
    - mvn -DskipTests clean package
  - stage: Run Tests
    if: branch = main OR type = pull_request
    cache:
      directories:
      - "$HOME/.m2"
    install:
    - docker-compose -f src/test/resources/docker-compose-test.yaml pull
    script:
    - mvn clean test
  - stage: Deploy Artifacts
    if: tag IS present
    branches:
      only:
        - main
    cache:
      directories:
        - "$HOME/.m2"
    script:
      - mvn deploy