name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      if: ${{ !github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Run Build
      run: mvn -DskipTests clean package
    - name: Run Tests
      env:
        OKTA_DUMMY_CI_PW: ${{ secrets.OKTA_DUMMY_CI_PW }}
        WCS_DUMMY_CI_PW: ${{ secrets.WCS_DUMMY_CI_PW }}
        OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
      run: |
        docker-compose -f src/test/resources/docker-compose-test.yaml pull
        mvn clean test
